receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128
  resource:
    attributes:
      - key: deployment.environment
        action: upsert
        value: prod
  transform/achievement:
    error_mode: ignore
    metric_statements:
      - context: resource
        statements:
          - set(attributes["service.namespace"], "yomu") where attributes["service.name"] == "be-achievement"
          - set(attributes["deployment.environment"], "prod") where attributes["service.name"] == "be-achievement"
          - set(attributes["service.name"], "be-achievement") where attributes["service.name"] == "Yomu"
    trace_statements:
      - context: resource
        statements:
          - set(attributes["service.namespace"], "yomu") where attributes["service.name"] == "be-achievement"
          - set(attributes["deployment.environment"], "prod") where attributes["service.name"] == "be-achievement"
          - set(attributes["service.name"], "be-achievement") where attributes["service.name"] == "Yomu"
    log_statements:
      - context: resource
        statements:
          - set(attributes["service.namespace"], "yomu") where attributes["service.name"] == "be-achievement"
          - set(attributes["deployment.environment"], "prod") where attributes["service.name"] == "be-achievement"
          - set(attributes["service.name"], "be-achievement") where attributes["service.name"] == "Yomu"
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: basic
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  prometheus:
    endpoint: 0.0.0.0:9464
    resource_to_telemetry_conversion:
      enabled: true

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, transform/achievement, batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, resource, transform/achievement, batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, transform/achievement, batch]
      exporters: [otlphttp/loki]
