{
 "title": "Achievement Monitoring",
 "tags": [
  "yomu",
  "achievement",
  "otel"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "application", "query": "be-achievement" }
  ]
 },
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_milliseconds_count{service_name=\"$application\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Quiz Completed Events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_milliseconds_count{service_name=\"$application\", uri=\"/api/events/quiz-completed\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Average HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_milliseconds_sum{service_name=\"$application\"}[1m])) by (uri) / sum(rate(http_server_requests_milliseconds_count{service_name=\"$application\"}[1m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}